---
- name: Allow ports through firewalld
  firewalld:
    state: enabled
    permanent: true
    immediate: true
    port: "{% if '/' in item_firewall_port|string %}{{ item_firewall_port|lower }}{% else %}{{item_firewall_port}}/tcp{% endif %}"
  when: firewall_provider is defined and firewall_provider == "firewalld"
  with_items: "{{ firewall_ports }}"
  loop_control:
    loop_var: "item_firewall_port"

- name: Allow ports through iptables
  iptables_raw:
    name: 'allow_tcp_{{ item_firewall_port }}'
    rules: '-A INPUT -p tcp -m tcp --dport "{{ item_firewall_port }}" -j ACCEPT'
  when: firewall_provider is defined and firewall_provider == "iptables"
  with_items: "{{ firewall_ports }}"
  loop_control:
    loop_var: "item_firewall_port"
